[project]
name = "crypto-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ccxt==4.5.9",
    "loguru==0.7.3",
    "numpy==2.3.5",
    "pandas==2.3.3",
    "pydantic==2.12.4",
    "pydantic-settings==2.12.0",
    "scikit-learn==1.7.2",
    "sqlalchemy==2.0.35",
]
